worldName: "world"
votes: 2
jailList: {}
jailPlayers: {}

# Sprawn Configuration

worlds:
    world:
        enabled: true
        overrideworldborder: true
        shape: ELLIPTICAL
        x-radius: 5000
        z-radius: 5000
        center-x: 0
        center-z: 0
        spawnrotation: 1h30m00s
    nether:
        enabled: false
    the_end:
        enabled: false

