name: Civrealms
main: com.jpmiii.Civrealms.Civrealms
version: 0.3.0
depend: [Vault]
commands:
   civ:
      description: reloads config
      usage: /reload
      permission-message: you cant do that
   jjail:
      description: sets jail loc
      usage: /jjail <jail name>
      permission-message: you cant do that
   bad:
      description: bans player if less that a day old
      usage: /bad <player name>
      permission-message: you cant do that
   biol:
      description: list biomes in log
      usage: /biol
      permission-message: you cant do that
