name: Civrealms
main: com.jpmiii.Civrealms.Civrealms
version: 0.1.2
depend: [Vault]
commands:
   civ:
      description: reloads config
      usage: /reload
      permission-message: you cant do that
   jjail:
      description: sets jail loc
      usage: /jjail jailname
      permission-message: you cant do that
